### ISSUE TITLE
Bluetooth doesn't retry after flight mode.

### ISSUE THREAD

**Issue by abranson** [abranson/rockpool#31]
Rockpoold needs to be restarted after flight mode before it can reconnect to the watch.

**Comment by Fuzzillogic** [comment]
Today my watch didn't reconnect, even after more than half an hour after disabling flight mode. Dis- and reenabling bluetooth on the phone caused it to reconnect within seconds, so the service was still running. I wonder if QTimer is the best solution for the reconnect timer. What happens when the phone goes into power save mode? Is QTimer still functional? An alternative may be to use [libiphb](https://git.merproject.org/mer-core/libiphb), as is used in [kitchen timer](https://github.com/tanghus/kitchen-timer-qml).

**Comment by abranson** [comment]
I remember reading about that problem somewhere. I've tried simplifying the bluetooth connection a bit in a recent commit (2e069fbfbb9a5d0a190ec4837ddae01d0926cce6), but if that doesn't help then I think a change of timer might be the next thing to try. Maybe we need to make it simpler to restart the service in the meantime.
