### ISSUE TITLE
Settings pages of apps are not visible

### ISSUE THREAD

**Issue by BjoernRuberg** [abranson/rockpool#56]
I have this bug for six weeks now. I could not get rid of it by deleting my ~/.local/share/rockpoold dir. That is odd, because it is likely a configuration problem. Otherwise others would have reported.

Every settings page of any app does not become visible anymore. Very intersting: if I rotate my phone to landscape, I often start to see parts of the page. When I afterwards rotate it back to portrait, the settings page is suddenly visible as it should be. I can work with it itoo.
This makes be believe that the page is rendered ouside of the screen initially.

However, this trick does only work one time. When I go into the settings of another app (or the same one), I cannot get to the setings page no matter how much I rotate the device. I have to restart rockpool to be able to do it again.

**Comment by rufferson** [comment]
yes, it's well known bug related to the migration of the WebView sailfish widget from webkit to geko and underlying modifications in the QtMozEmbed code (which is used in rockpool client).
I've been waiting for SDK 2.0.5 release with this component and now am working on migration to the new widget.

**Comment by rufferson** [comment]
btw you'll see the page if you rotate the screen (and back bcz geometry change is also borken) - but only once on each client start. That's how it behaves after those _underlying modifications_

**Comment by rufferson** [comment]
Just to keep you up-to-date - in Jolla 2.0.5.x qml mozview is still broken and guys heavily modified it from simplistic original implementation to fit sailfish needs (like screengrabbing, vkb adjustment, etc.) so it's not that trivial to fix it with my limited knowledge of what they need. There's inside info it will be fixed in the next release where Jolla will also start using it for internal apps.

**Comment by alan-morford** [comment]
Interestingly the Sailfish update to 2.2.1 has fixed settings viewing.  Unfortunately, it won't accept input.  No touch response other than scrolling.

**Comment by JakobBerg** [comment]
On Sailfish 3.1.0.11 with PTS 4.4.0-rbl I can click on settings for both watch apps as well as watch faces (as also referenced: https://github.com/abranson/rockpool/issues/78 )

when clicking settings for an app, the appropriate app will load on the watch, but rockpool will just display an http link instead of loading the content of the link.

**Comment by abranson** [comment]
I've reverted back to WebKit in the latest release, and the settings pages work ok again. It's not ideal but the Silica Webview still isn't finished and doesn't work properly.
